# Use root/example as user/password credentials
version: '3.5'

services:

  db:
    image: mariadb/server:10.3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: dispersao_sequences
      MYSQL_USER: ${MYSQL_DISPERSAO_USER}
      MYSQL_PASSWORD: ${MYSQL_DISPERSAO_PASSWORD}
    volumes:
      - ./mysql/dispersao.sql:/docker-entrypoint-initdb.d/dispersao.sql

  cms:
    build: ./cms
    image: dispersao/cms
    depends_on:
      - db
      - redis
    environment:
      - database_host=db
      - redis_host=redis
      - mysql_dispersao_user=${MYSQL_DISPERSAO_USER}
      - mysql_dispersao_password=${MYSQL_DISPERSAO_PASSWORD}
      - redis_password=${REDIS_PASSWORD}
    ports:
      - "1337:1337"

  master:
    build: ./dispersao-master
    command: npm start -- --api_url ${MASTER_API_URL} --api_user ${MASTER_USER} --api_password ${MASTER_PASSWORD}
    image: dispersao/master
    depends_on:
      - db
      - cms
    ports:
      - 3000:3000
      - 3001:3001

  redis:
    image: redis:alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - 6379:6379
    volumes:
      - $PWD/redis-data:/data
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
  
    environment:
      - REDIS_REPLICATION_MODE=master
