FROM node:12.6

WORKDIR /

# RUN git clone -b docker https://github.com/dispersao/cms.git
VOLUME ["/Users/maysala/DOCS/GIT_REPOS/dispersao/cms"]

WORKDIR /cms

RUN ls

# RUN npm ci

# CMD ["npm", "run", "develop"]
