version: '3.5'

services:

  db:
    image: mariadb/server:10.3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: dispersao_sequences
      MYSQL_USER: dispersao_user
      MYSQL_PASSWORD: ${MYSQL_DISPERSAO_PASSWORD}
    volumes:
      - ${MYSQL_DUMP_FILE}:/docker-entrypoint-initdb.d/dispersao.sql
    ports:
      - "3306:3306"

  cms:
    image: node:12.6
    command: npm run develop
    depends_on:
      - db
      - redis
    environment:
      - database_host=db
      - redis_host=redis
      - mysql_dispersao_password=${MYSQL_DISPERSAO_PASSWORD}
      - redis_password=${REDIS_PASSWORD}
    ports:
      - "1337:1337"
    volumes:
      - ${CMS_SRC}:/cms
    working_dir: /cms


#  socket-server:
#    image: node:12.6
#    command: sh runsocket.sh
#    ports:
#      - 8081:8081
#      - target: 7400
#        published: 7400
#        protocol: udp
#        mode: host
#    volumes:
#      - ${SOCKET_SERVER_SRC}:/socket-server
#    working_dir: /socket-server

  master:
    image: node:12.6
    command: npm start
    depends_on:
      - db
#      - socket-server
    ports:
      - 3000:3000
      - 3001:3001
    volumes:
      - ${MASTER_SRC}:/dispersao-master
    working_dir: /dispersao-master

  redis:
    image: redis:alpine
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - 6379:6379
    volumes:
      - $PWD/redis-data:/data
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
  
    environment:
      - REDIS_REPLICATION_MODE=master
