version: '3.5'

services:

  db:
    image: mariadb/server:10.3
    # restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: dispersao_sequences
      MYSQL_USER: dispersao_user
      MYSQL_PASSWORD: ${MYSQL_DISPERSAO_PASSWORD}
    volumes:
      - ${MYSQL_DUMP_FILE}:/docker-entrypoint-initdb.d/dispersao.sql
    ports:
      - "${MYSQL_PORT_EXT}:${MYSQL_PORT_INT}"

  cms:
    image: node:12.6
    # command: npm run develop
    command:  node --inspect=0.0.0.0:9229 ./node_modules/strapi/bin/strapi.js develop
    depends_on:
      - db
      - redis
    environment:
      - database_host=db
      - redis_host=redis
      - mysql_dispersao_user=${MYSQL_DISPERSAO_USER}
      - mysql_dispersao_password=${MYSQL_DISPERSAO_PASSWORD}
      - mysql_port=${MYSQL_PORT_INT}
      - redis_password=${REDIS_PASSWORD}
      - redis_port=${REDIS_PORT_INT}
  
    ports:
      - "1337:1337"
    volumes:
      - ${CMS_SRC}:/cms
    working_dir: /cms

  master:
    image: node:12.6
    command: npm start -- --api_url ${MASTER_API_URL} --api_user ${MASTER_USER} --api_password ${MASTER_PASSWORD}
    depends_on:
      - db
      - cms
#      - socket-server
    ports:
      - 3000:3000
      - 3001:3001
    volumes:
      - ${MASTER_SRC}:/dispersao-master
    working_dir: /dispersao-master

  redis:
    image: redis:alpine
    # restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT_EXT}:${REDIS_PORT_INT}"
    volumes:
      - $PWD/redis-data:/data
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
