version: '3.5'

services:

  db:
    image: mariadb/server:10.3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: dispersao_sequences
      MYSQL_USER: dispersao_user
      MYSQL_PASSWORD: ${MYSQL_DISPERSAO_PASSWORD}
    volumes:
      - ${MYSQL_DUMP_FILE}:/docker-entrypoint-initdb.d/dispersao.sql
    ports:
      - "6633:3306"

  cms:
    build: ./cms
    image: dispersao/cms
    depends_on:
      - db
    environment:
      - database_host=db
      - redis_host=redis
      - mysql_dispersao_password=${MYSQL_DISPERSAO_PASSWORD}
      - redis_password=${REDIS_PASSWORD}
    ports:
      - "1337:1337"
    working_dir: /cms

  redis:
    image: redis:alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - 6379:6379
    volumes:
      - $PWD/redis-data:/data
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
  
    environment:
      - REDIS_REPLICATION_MODE=master  
