version: '3.5'

services:

  db:
    image: mariadb/server:10.3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DISPERSAO_DB}
      MYSQL_USER: ${MYSQL_DISPERSAO_USER}
      MYSQL_PASSWORD: ${MYSQL_DISPERSAO_PASSWORD}
    volumes:
      - ${MYSQL_DUMP_FILE}:/docker-entrypoint-initdb.d/dispersao.sql
    ports:
      - "${MYSQL_PORT_EXT}:${MYSQL_PORT_INT}"

  cms:
    build: ./cms
    image: dispersao/cms
    depends_on:
      - db
      - redis
    environment:
      - database_host=db
      - redis_host=redis
      - mysql_dispersao_db=${MYSQL_DISPERSAO_DB}
      - mysql_dispersao_user=${MYSQL_DISPERSAO_USER}
      - mysql_dispersao_password=${MYSQL_DISPERSAO_PASSWORD}
      - mysql_port=${MYSQL_PORT_INT}
      - redis_password=${REDIS_PASSWORD}
      - redis_port=${REDIS_PORT_INT}
      - ADMIN_JWT_SECRET=${JWT_SECRET}
      - NODE_ENV=production
      - PUBLIC_URL=http://movieserver.dispersao.net
    ports:
      - 1337:1337
    working_dir: /cms

  redis:
    image: redis:alpine
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT_EXT}:${REDIS_PORT_INT}"
    volumes:
      - $PWD/redis-data:/data
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master  
