version: '3.5'

services:

  db:
    image: mariadb/server:10.3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: dispersao_sequences
      MYSQL_USER: dispersao_user
      MYSQL_PASSWORD: ${MYSQL_DISPERSAO_PASSWORD}
    volumes:
      - ${MYSQL_DUMP_FILE}:/docker-entrypoint-initdb.d/dispersao.sql

  cms:
    build: ./cms
    image: dispersao/cms
    depends_on:
      - db
    environment:
      - database_host=db
      - mysql_dispersao_password=${MYSQL_DISPERSAO_PASSWORD}
    ports:
      - "1337:1337"
    working_dir: /cms
